Update EMU-internal-repo-migration.yaml

diff --git a/.github/workflows/EMU-internal-repo-migration.yaml b/.github/workflows/EMU-internal-repo-migration.yaml
--- a/.github/workflows/EMU-internal-repo-migration.yaml
+++ b/.github/workflows/EMU-internal-repo-migration.yaml
@@ -72,14 +72,18 @@ jobs:
 
           echo "Creating or pushing to $DEST_ORG/$DEST_REPO..."
           if ! gh repo view $DEST_ORG/$DEST_REPO &>/dev/null; then
+            echo "Repository $DEST_ORG/$DEST_REPO already exists. Failing the job."
+            exit 1
+          else           
+            echo "Repository does not exist. Proceeding with creation..."
             gh repo create "$DEST_ORG/$DEST_REPO" --private --description "Migrated from $SOURCE_ORG/$SRC_REPO"
             echo "Waiting for GitHub to register the new repository..."
-            sleep 10
-          
+            sleep 10 
           fi
 
           git push --mirror https://x-access-token:${GH_TOKEN}@github.com/$DEST_ORG/$DEST_REPO.git
           cd .. && rm -rf $SRC_REPO.git
+          
       - name: Set Admin and Metadata
         run: |
           echo "Setting admin access for $REPO_ADMIN..."
